name: Code Summarizer
on:
  push:
permissions:
  contents: write
jobs:
  summarizer:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repo
        uses: actions/checkout@v4

      - name: Get diff from repo
        run: |
          if git rev-parse HEAD~1 > /dev/null 2>&1; then
            git diff HEAD~1 HEAD > diff.txt
          else
            git diff --root HEAD > diff.txt
          fi

      - name: Call AI API to summarize diff
        run: |
          diff=$(cat diff.txt)
          payload=$(jq -n --arg diff "$diff" '{
              "model": "llama-3.3-70b-versatile",
              "messages": [
              {
                "role": "system",
                "content": "Imagine you are developer summarizing what the code does. Return a bulleted list that summarizes the function of the code with the date, to format a changelog file. Your analysis for a small amount of code shouldnt be long"
              }, 
              {
                "role": "user",
                "content": $diff
              }
              ]
            }'  
          )

          curl https://api.groq.com/openai/v1/chat/completions -s \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.GROK_API }}" \
            -d  "$payload" > response.txt

      - name: Modify changelog file
        run: jq -r '.choices[0].message.content' response.txt >> CHANGELOG.md

      - name: Push the changelog file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Chore: Updating the changelog"
          file_pattern: "CHANGELOG.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
